web_url:
  default: "http://ketedev.nzte.govt.nz"
  description: "The url that you would like to point the theme to. Used across the theme to link back to Kete webapp."
forum_url:
    default: "https://forumdev.nzte.govt.nz"
    description: "The url of the forum instance"